library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
obj = readRDS("../zebTestis.rds")
markers=FindMarkers(obj,ident.1 = '5', ident.2 = '3', only.pos=F,min.pct=0.2)
gene=rownames(markers)
markers=cbind(gene,markers)
write.table(markers,file="SPG_subPopulation_markerGenes.tsv",sep="\t",quote=F,row.names=F)
